### ISSUE TITLE
A confusion about Generating Gaussian Kernel

### ISSUE THREAD

**Issue by Zixuan-Zhu** [Yao-DD/S3N#11]
Thanks for your sharing!
When generating the Gaussian Distance in sse_net.py, line 27:
```
return np.exp(-4 * np.log(2) * ((x - x0) ** 2 + (y - y0) ** 2) / fwhm ** 2)
```
I have a confusion about the meaning  of  ``` -4 * np.log(2)  ``` 
Could you solve my confusion? Thank you

**Comment by Yao-DD** [comment]
-4 * np.log(2) is just an empirical initialization of k(v', v) in Eq(7) and Eq(8).

**Comment by Zixuan-Zhu** [comment]
Thanks a lot!
