### ISSUE TITLE
Type: TypeError Message: The returns of Nest module "image_transform" should be type of "Callable". Got "Compose

### ISSUE THREAD

**Issue by hongbo-sun** [Yao-DD/S3N#9]
Excuse me, how to deal with the following exception? Thank you very much.
I have followed the "You can comment out lines 114-122 in 'Nest/src/nest/modules.py' and reinstall Nest." to work out the problem of "Please check if some important params of Nest module ... have been forgotten in use.". But, there is another exception as follows.

Exception occurred during resolving:
Type: TypeError
Message: The returns of Nest module "image_transform" should be type of "Callable". Got "Compose(
RandomResizedCrop(size=(448, 448), scale=(0.5, 1), ratio=(0.75, 1.3333), interpolation=PIL.Image.BILINEAR)
RandomHorizontalFlip(p=0.5)
ToTensor()
Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)".
Traceback:
[1] File "./S3N/datasets.py", line 77, in function "fetch_data"
train_transform = transform(augmentation=train_augmentation) if transform else None

**Comment by akira-l** [comment]
Get the same error here. How to solve this ?

**Comment by yifanpu001** [comment]
same error here. I still have not solve this problem
